version: '3.4'
networks:
  eq.websocket:

services:
  eq.websocket:
    image: ${DOCKER_REGISTRY-}eqwebsocket
    build:
      context: .
      dockerfile: EQ.WebSocket/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
    networks: 
      - eq.websocket